### PR TITLE
Allow 'path' at [widget] level

### LINKED ISSUE #29: url, path and context-path are allowed at widget level
https://apps.axibase.com/chartlab/928dc94d/4/

### PR DESCRIPTION
**Pull request by PolinaShneider**
Closes #29

### CODE REVIEW

**Comment by annstriganova** [comment]
Update docs, please.

**Comment by PolinaShneider** [comment]
You mean `descriptions.md` or docs somewhere else?

**Comment by PolinaShneider** [comment]
If you mean [this](https://axibase.com/docs/charts/widgets/shared/#url), `path`, `context-path` and `url` are already considered as `[widget]` settings

**Comment by annstriganova** [comment]
@PolinaShneider, ok, in this case, no changes are necessary.

**Pull request merged**
